project_name: testergit

dist: ./dist

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - id: release-build
    binary: testergit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X 'github.com/sfarosu/testergit/cmd/version.BuildDate={{.Date}}'
      - -X 'github.com/sfarosu/testergit/cmd/version.GitShortHash={{.ShortCommit}}'

archives:
  - id: release-archive
    builds:
      - release-build
    format: tar.gz

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "SNAPSHOT-{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  ids:
    - release-archive
  github:
    owner: sfarosu
    name: testergit

dockers:
  - dockerfile: Dockerfile-Goreleaser
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "docker.io/sfarosu/testergit:latest"
      - "docker.io/sfarosu/testergit:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - scripts

  - dockerfile: Dockerfile-Goreleaser
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "docker.io/sfarosu/testergit:latest"
      - "docker.io/sfarosu/testergit:{{ .Tag }}-arm64v8"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - scripts

docker_manifests:
- name_template: "docker.io/sfarosu/testergit:{{ .Version }}"
  image_templates:
  - "docker.io/sfarosu/testergit:{{ .Tag }}-amd64"
  - "docker.io/sfarosu/testergit:{{ .Tag }}-arm64v8"
