FROM alpine:3.19
COPY testergit /app/
COPY ./scripts/ ./scripts

RUN chown -R 10001:root /app && \
    chgrp -R 0 /app && \
    chmod -R g=u /app /etc/passwd && \
    chmod -R a+x-w /app/scripts && \
    chmod a+x-w /app/testergit

EXPOSE 8080

ENTRYPOINT [ "./scripts/uid_entrypoint.sh" ]

USER 10001

CMD [ "./testergit" ]
