FROM alpine:3.19

WORKDIR /app

COPY testergit /app/
COPY scripts /app/
COPY scripts/uid_entrypoint.sh /app/scripts/

EXPOSE 8080

ENTRYPOINT [ "/app/scripts/uid_entrypoint.sh" ]

USER 10001

CMD [ "./app/testergit" ]
